name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run editorconfig
      - run: npm run lint
      - run: npm run stylelint
      - run: npm run prettier
      - run: npm run test:check
